sm8250-common: build the required extphone packages
E AndroidRuntime: Process: com.qti.phone, PID: 2544
11-19 22:49:58.182  2544  2544 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qti/extphone/IExtPhone$Stub;
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4497)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2162)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7894)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
11-19 22:49:58.182  2544  2544 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.qti.extphone.IExtPhone$Stub
11-19 22:49:58.182  2544  2544 E AndroidRuntime: 	... 13 more
11-19 22:49:58.453  3231  3231 E AndroidRuntime: FATAL EXCEPTION: main
11-19 22:49:58.453  3231  3231 E AndroidRuntime: Process: com.qti.phone, PID: 3231
11-19 22:49:58.453  3231  3231 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qti/extphone/IExtPhone$Stub;
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4497)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2162)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7894)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
11-19 22:49:58.453  3231  3231 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.qti.extphone.IExtPhone$Stub
11-19 22:49:58.453  3231  3231 E AndroidRuntime: 	... 13 more

Signed-off-by: IGaganpreetSingh <gaganpannu83@gmail.com>